### ISSUE TITLE
Failure to Parse Capitalized Form: urn:cite:hmt:msA.246v Ὀδυσσείᾳ

### ISSUE THREAD

**Issue by mwauke** [homermultitext/lexmapping#15]
urn:cts:greekLit:tlg5026.msA.hmt:18.129@Ὀδυσσείᾳ[1]
urn:cts:greekLit:tlg5026.msA.hmt:18.133@Ὀδυσσείᾳ[1]

wrapped in a title element and still failing

**Comment by neelsmith** [comment]
added
