### ISSUE TITLE
Failure to parse ἐθέλωσ'

### ISSUE THREAD

**Issue by Eumaeus** [homermultitext/lexmapping#22]
urn:cts:greekLit:tlg0012.tlg001.msA:19.71@ἐθέλωσ'[1]

https://github.com/hmteditors/2015office5/tree/master/editions/Iliad

(Apostrophe confirmed to be the same apostrophe that is passing validation elsewhere.)

**Comment by neelsmith** [comment]
The infamous terminal sigma bug, now fixed.
