### ISSUE TITLE
Failure to Parse Capitalized Form: urn:cite:hmt:msA.249r Ἀλκμανικοῦ

### ISSUE THREAD

**Issue by scnevi17** [homermultitext/lexmapping#23]
urn:cts:greekLit:tlg5026.msA.hmt:18.186@Ἀλκμανικοῦ[1]

Personal adj, not tagged as a persName

**Comment by mwauke** [comment]
Similarly, Ἀλκμανικῷ on 249r does not parse.

urn:cts:greekLit:tlg5026.msA.hmt:18.186@Ἀλκμανικῷ

**Comment by neelsmith** [comment]
added
