### ISSUE TITLE
Failure to parse capitalized form: urn:cite:hmt:msA.252v Μασσαλιωτικῇ

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/lexmapping#34]
urn:cts:greekLit:tlg5026.msA.hmt:19.2015office5_2

**Comment by mwauke** [comment]
Similarly, Μασσαλέωτικῆ (249v) fails to parse. 

urn:cts:greekLit:tlg5026.msAint.hmt:18.47

**Comment by neelsmith** [comment]
added Μασσαλιωτικῇ.  

Should Μασσαλέωτικῆ be a "sic" ?
