### ISSUE TITLE
Failure to Parse Titles Because they are also Places: urn:cite:hmt:msA.253r χίαι   urn:cite:hmt:msA.253r μασσαλιωτικηῖ

### ISSUE THREAD

**Issue by ulalian** [homermultitext/lexmapping#36]
urn:cts:greekLit:tlg0012.tlg001.msA:@ χίαι[1]
urn:cts:greekLit:tlg0012.tlg001.msA:@ μασσαλιωτικηῖ[1]

**Comment by neelsmith** [comment]
Note that while the MS writes all sigmas adscript, we transcribe with iota subscript where that is conventional in modern orthography.  Please correct the XML source edition.
