### ISSUE TITLE
Failure to parse: urn:cite:hmt:msA.250r ᾀσθεῖσαν

### ISSUE THREAD

**Issue by brclar15** [homermultitext/lexmapping#47]
urn:cts:greekLit:tlg5026.msA.hmt:18.204

Valid from from ἀείδω, the fem acc sing aorist pass participle. 
We've consulted with Professor Ebbott on this one

**Comment by neelsmith** [comment]
parses in CLI morpheus

**Comment by neelsmith** [comment]
It was a Unicode issue:  now parses correctly from MOM
