### ISSUE TITLE
NEW FORM: urn:cite:hmt:msA.249r ὀλίσσων

### ISSUE THREAD

**Issue by brclar15** [homermultitext/lexmapping#54]
urn:cts:greekLit:tlg5026.msA.hmt:18.188@ὀλίσσων[1]

The scholion says that this is a third form of the comparative from ὀλίγος. 
This form does not appear in the LSJ.

**Comment by brclar15** [comment]
urn:cts:greekLit:tlg5026.msA.hmt:18.188@ὀλιγίων[1]

The scholion says that this is a second form of the comparative from ὀλίγος. 
This form does not appear in the LSJ.

**Comment by neelsmith** [comment]
Awesome!  Dealing with it under urn:cite:hmt:normalizedcase.30
