### ISSUE TITLE
NEW FORM: urn:cite:hmt:msA.252r  δέειλη

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/lexmapping#61]
urn:cts:greekLit:tlg5026.msA.hmt:19.2015office4_1@δέειλη

Scholion is discussing the etymology of δῆλος, specifically the alternative form of δήλη, δεείλη.  Erbse changed δέειλη to δεέλη since the former does not appear in the LSJ nor does it parse in Morpheus, but the second form does. However, the scholion's explanation of the etymology, from "ἐνδεῖν τῇ ἕλῃ", makes it seem that δεείλη could be a legitimate form since ἕλη itself is an alternative form of εἵλη.

**Comment by neelsmith** [comment]
But it would have to be accented δεέιλη.  So should this be flagged with "sic"?

**Comment by cjschu17** [comment]
We tagged it with "sic"
