### ISSUE TITLE
Failed to Parse: urn:cite:hmt:msA.259v προσβλέψων

### ISSUE THREAD

**Issue by brclar15** [homermultitext/lexmapping#80]
This looks like a legitimate form, and is perhaps its first occurrence. 
Appears to be the future nom masc sing future participle of προσβλέπω

**Comment by neelsmith** [comment]
Odd.  προσβλεψω (fut. act. ind.) parses correctly, but fut.act.ptcpl. does not.

Morpheus bug.

**Comment by neelsmith** [comment]
added
