### ISSUE TITLE
Failed to Parse form: urn:cite:hmt:msA.259r αθετουμενοι

### ISSUE THREAD

**Issue by brclar15** [homermultitext/lexmapping#82]
αθετούμενοι appears to be a masc plural nom participle from  ἀθετέω. It fails in both Perseus and morpheus

**Comment by neelsmith** [comment]
No it doesn't: it passes morpheus fine.  Make this a byzortho issue, but be sure to get both breathing and accent correct:  ἀθετούμενοι
