### ISSUE TITLE
Failure to parse ζητοῦσι urn:cite:hmt:msA.101r

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/lexmapping#89]
urn:cts:greekLit:tlg5026.msA.hmt:8.20@ζητοῦσι[1]

it is a word but morpheus can't recognize the form

**Comment by neelsmith** [comment]
parses from CLI

**Comment by neelsmith** [comment]
parses from CLI

**Comment by neelsmith** [comment]
added
