### ISSUE TITLE
Failure to parse urn:cite:hmt:msA.101r εὐλαβεῖσθαι

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/lexmapping#90]
urn:cts:greekLit:tlg5026.msA.hmt:8.25@εὐλαβεῖσθαι[1]

morpheus doesn't recognize it but it's in the LSJ

**Comment by neelsmith** [comment]
parses from CLI

**Comment by neelsmith** [comment]
Morpheus is inconsistent in parsing contract verbs!  Sequence of parsing other words can matter!

Treating htis as modern ortho problem.
