### ISSUE TITLE
Failed to Parse: urn:cite:hmt:msA.248v Κυκλικοῖς

### ISSUE THREAD

**Issue by brclar15** [homermultitext/lexmapping#95]
urn:cts:greekLit:tlg5026.msA.hmt:18.164@Κυκλικοῖς[1]

should the masculine  dative plural of κυκλικός.
It is capitalized with the idea that it refers to the Cyclic Poets, but scholarship is divided on whether or not it just means vulgar or common

**Comment by neelsmith** [comment]
added
