### ISSUE TITLE
Failed to Parse urn:cite:hmt:msA.191r δυσδιαχείριστον

### ISSUE THREAD

**Issue by brclar15** [homermultitext/lexmapping#97]
urn:cts:greekLit:tlg5026.msA.hmt:15.16@δυσδιαχείριστον[1]

DIndorf agrees with our reading. It seems to be an unattested compound by adding δυσδια to either χείριστος or to χείρων

**Comment by neelsmith** [comment]
duplicate entry with https://github.com/homermultitext/lexmapping/issues/67
